-- CreateEnum
CREATE TYPE "OTPENUM" AS ENUM ('AUTH', 'RESETPASSWORD', 'PAYMENT');

-- CreateTable
CREATE TABLE "OTP" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "isForUser" BOOLEAN NOT NULL,
    "code" INTEGER NOT NULL,
    "isExpired" BOOLEAN NOT NULL,
    "type" "OTPENUM" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatadAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "OTP_pkey" PRIMARY KEY ("id")
);
